export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM'

export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING'
export const CART_SAVE_PAYMENY_METHOD = 'CART_SAVE_PAYMENY_METHOD'

export const CART_EMPTY = 'CART_EMPTY'
