const data = {
    products: [
      {
        _id: '1',
        name: 'Product 1',
        category: 'Categ-x',
        image: '/images/p1.jpg',
        price: 400,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Product 2',
        category: 'Brandname',
        image: '/images/p2.jpg',
        price: 23.75,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Product 3',
        category: 'Testing',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Product 4',
        category: 'Name_BRAND',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Product 5',
        category: 'Prod-Name',
        image: '/images/p5.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Product 6',
        category: 'B-NAME',
        image: '/images/p6.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;